include: package:lints/recommended.yaml
linter:
  rules:
    non_constant_identifier_names: false
    constant_identifier_names: false
analyzer:
  exclude: [build/**, generators/**]
  strong-mode:
    implicit-casts: false
