name: objd
version: 0.3.0

author: Stevertus <stevertusyt@gmail.com>
homepage: https://stevertus.com
repository: https://github.com/Stevertus/objD
issue_tracker: https://github.com/Stevertus/objD/issues
documentation: https://objd.stevertus.com
description: objd is an Object Oriented framework for Building Minecraft Datapacks with ease
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
  meta: ^1.1.7
  colorize: ^2.0.0
  gson: ^0.1.2
dev_dependencies:
  pedantic: ^1.8.0