name: objd
version: 0.3.6

homepage: https://objd.stevertus.com
repository: https://github.com/Stevertus/objD
issue_tracker: https://github.com/Stevertus/objD/issues
documentation: https://objd.stevertus.com/guide
description: objd is an Object Oriented framework for Building Minecraft Datapacks with ease
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  meta: ^1.2.4
  colorize: ^2.0.0
  archive: ">=2.0.13"
  gson: ^0.1.4
dev_dependencies:
  pedantic: ^1.9.2
