name: web_example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 objd:
  path: ../

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
